package com.voicedirection.glass.qa

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import com.voicedirection.glass.alerts.AlertChannel
import com.voicedirection.glass.diagnostics.DiagnosticsLogger
import com.voicedirection.glass.model.CallerDirection
import com.voicedirection.glass.model.DetectionFeedbackSummarizer
import com.voicedirection.glass.model.DetectionLatencySummarizer
import com.voicedirection.glass.model.DirectionValidationSummarizer
import com.voicedirection.glass.model.FalsePositiveRunSummarizer
import com.voicedirection.glass.storage.PreferencesVoiceDirectionRepository

class EvidenceSnapshotReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        val result = runCatching {
            val snapshot = PreferencesVoiceDirectionRepository(context).loadSnapshot()
            val feedback = DetectionFeedbackSummarizer.summarize(snapshot.feedback)
            val latency = DetectionLatencySummarizer.summarize(snapshot.events)
            val direction = DirectionValidationSummarizer.summarize(snapshot.directionValidationTrials)
            val delivery = snapshot.latestAlertDeliverySnapshot
            val audioDirectionSample = snapshot.latestAudioDirectionSample
            val falsePositive = FalsePositiveRunSummarizer.summarize(
                run = snapshot.falsePositiveRun,
                feedback = snapshot.feedback,
                nowMillis = System.currentTimeMillis(),
            )
            EvidenceSnapshotResult(
                passed = true,
                profileCount = snapshot.profiles.size,
                eventCount = snapshot.events.size,
                actionableEventCount = snapshot.events.count { event -> event.isActionable },
                microphoneDisclosureAccepted = snapshot.settings.microphoneDisclosureAccepted,
                microphoneDisclosureVersion = snapshot.settings.microphoneDisclosureVersion.ifBlank { "MISSING" },
                enabledAlertChannelCount = snapshot.settings.enabledAlertChannels.size,
                phoneNotificationEnabled = AlertChannel.PHONE_NOTIFICATION in snapshot.settings.enabledAlertChannels,
                phoneVibrationEnabled = AlertChannel.PHONE_VIBRATION in snapshot.settings.enabledAlertChannels,
                ttsEnabled = AlertChannel.TTS in snapshot.settings.enabledAlertChannels,
                metaDisplayEnabled = AlertChannel.META_DISPLAY in snapshot.settings.enabledAlertChannels,
                androidXrDisplayEnabled = AlertChannel.ANDROID_XR_DISPLAY in snapshot.settings.enabledAlertChannels,
                latencyEventCount = latency.eventsWithLatency,
                latestProcessingLatencyMillis = latency.latestLatencyMillis ?: -1L,
                averageProcessingLatencyMillis = latency.averageLatencyMillis ?: -1L,
                latencyOverTargetCount = latency.overTargetCount,
                feedbackCount = feedback.total,
                feedbackCorrect = feedback.correct,
                feedbackFalsePositive = feedback.falsePositive,
                feedbackWrongDirection = feedback.wrongDirection,
                feedbackWrongSpeaker = feedback.wrongSpeaker,
                directionTrialCount = direction.total,
                directionRequiredTrialsPerDirection = direction.requiredTrialsPerDirection,
                directionRequiredTotalTrials = direction.requiredTotalTrials,
                directionMissingTotalTrials = direction.missingTotalTrials,
                directionControlledTrialTargetComplete = direction.controlledTrialTargetComplete,
                directionMatched = direction.matched,
                directionMismatched = direction.mismatched,
                directionUnknownOrUnusable = direction.unknownOrUnusable,
                directionFrontTrials = direction.frontTrials,
                directionBackTrials = direction.backTrials,
                directionLeftTrials = direction.leftTrials,
                directionRightTrials = direction.rightTrials,
                directionFrontMissingTrials = direction.missingFrontTrials,
                directionBackMissingTrials = direction.missingBackTrials,
                directionLeftMissingTrials = direction.missingLeftTrials,
                directionRightMissingTrials = direction.missingRightTrials,
                directionFrontMatched = direction.front.matched,
                directionFrontMismatched = direction.front.mismatched,
                directionFrontUnknownOrUnusable = direction.front.unknownOrUnusable,
                directionBackMatched = direction.back.matched,
                directionBackMismatched = direction.back.mismatched,
                directionBackUnknownOrUnusable = direction.back.unknownOrUnusable,
                directionLeftMatched = direction.left.matched,
                directionLeftMismatched = direction.left.mismatched,
                directionLeftUnknownOrUnusable = direction.left.unknownOrUnusable,
                directionRightMatched = direction.right.matched,
                directionRightMismatched = direction.right.mismatched,
                directionRightUnknownOrUnusable = direction.right.unknownOrUnusable,
                latestCuePresent = snapshot.latestGlassesCue != null,
                latestCueDirection = snapshot.latestGlassesCue?.direction ?: CallerDirection.UNKNOWN,
                latestDeliveryPresent = delivery != null,
                latestDeliverySource = delivery?.source?.name ?: "MISSING",
                latestDeliveryTotalCount = delivery?.totalCount ?: 0,
                latestDeliveryDeliveredCount = delivery?.deliveredCount ?: 0,
                latestDeliveryPhoneNotification = delivery?.statusFor(AlertChannel.PHONE_NOTIFICATION)?.name ?: "MISSING",
                latestDeliveryPhoneVibration = delivery?.statusFor(AlertChannel.PHONE_VIBRATION)?.name ?: "MISSING",
                latestDeliveryTts = delivery?.statusFor(AlertChannel.TTS)?.name ?: "MISSING",
                latestDeliveryMetaDisplay = delivery?.statusFor(AlertChannel.META_DISPLAY)?.name ?: "MISSING",
                latestDeliveryAndroidXrDisplay = delivery?.statusFor(AlertChannel.ANDROID_XR_DISPLAY)?.name ?: "MISSING",
                latestAudioDirectionSamplePresent = audioDirectionSample != null,
                latestAudioDirectionStatus = audioDirectionSample?.status?.name ?: "MISSING",
                latestAudioDirectionEvidenceLevel = audioDirectionSample?.evidenceLevel?.name ?: "MISSING",
                latestAudioDirectionDirection = audioDirectionSample?.direction ?: CallerDirection.UNKNOWN,
                latestAudioDirectionConfidenceBucket = audioDirectionSample
                    ?.let { sample -> DiagnosticsLogger.confidenceBucket(sample.confidence) }
                    ?: "MISSING",
                latestAudioDirectionSampleRateHz = audioDirectionSample?.sampleRateHz ?: -1,
                latestAudioDirectionSamplesRead = audioDirectionSample?.samplesRead ?: 0,
                latestAudioDirectionMicrophoneInventoryCaptured = audioDirectionSample
                    ?.microphoneInventoryCaptured ?: false,
                latestAudioDirectionAvailableMicrophoneCount = audioDirectionSample?.availableMicrophoneCount ?: 0,
                latestAudioDirectionAvailablePositionKnownCount = audioDirectionSample
                    ?.availablePositionKnownCount ?: 0,
                latestAudioDirectionAvailableOrientationKnownCount = audioDirectionSample
                    ?.availableOrientationKnownCount ?: 0,
                latestAudioDirectionActiveMicrophoneCaptured = audioDirectionSample
                    ?.activeMicrophoneCaptured ?: false,
                latestAudioDirectionActiveMicrophoneCount = audioDirectionSample?.activeMicrophoneCount ?: -1,
                latestAudioDirectionActiveChannelMappingCount = audioDirectionSample
                    ?.activeChannelMappingCount ?: -1,
                serviceBridgePresent = snapshot.latestServiceAutomationBridge != null,
                falsePositiveRunPresent = falsePositive.run != null,
                falsePositiveRunActive = falsePositive.run?.active ?: false,
                falsePositiveVerdict = falsePositive.verdict.name,
                message = "pass",
            )
        }.getOrElse { error ->
            EvidenceSnapshotResult(
                passed = false,
                profileCount = 0,
                eventCount = 0,
                actionableEventCount = 0,
                microphoneDisclosureAccepted = false,
                microphoneDisclosureVersion = "ERROR",
                enabledAlertChannelCount = 0,
                phoneNotificationEnabled = false,
                phoneVibrationEnabled = false,
                ttsEnabled = false,
                metaDisplayEnabled = false,
                androidXrDisplayEnabled = false,
                latencyEventCount = 0,
                latestProcessingLatencyMillis = -1L,
                averageProcessingLatencyMillis = -1L,
                latencyOverTargetCount = 0,
                feedbackCount = 0,
                feedbackCorrect = 0,
                feedbackFalsePositive = 0,
                feedbackWrongDirection = 0,
                feedbackWrongSpeaker = 0,
                directionTrialCount = 0,
                directionRequiredTrialsPerDirection = DirectionValidationSummarizer.CONTROLLED_TRIALS_PER_DIRECTION,
                directionRequiredTotalTrials = DirectionValidationSummarizer.CONTROLLED_TRIALS_PER_DIRECTION * 4,
                directionMissingTotalTrials = DirectionValidationSummarizer.CONTROLLED_TRIALS_PER_DIRECTION * 4,
                directionControlledTrialTargetComplete = false,
                directionMatched = 0,
                directionMismatched = 0,
                directionUnknownOrUnusable = 0,
                directionFrontTrials = 0,
                directionBackTrials = 0,
                directionLeftTrials = 0,
                directionRightTrials = 0,
                directionFrontMissingTrials = DirectionValidationSummarizer.CONTROLLED_TRIALS_PER_DIRECTION,
                directionBackMissingTrials = DirectionValidationSummarizer.CONTROLLED_TRIALS_PER_DIRECTION,
                directionLeftMissingTrials = DirectionValidationSummarizer.CONTROLLED_TRIALS_PER_DIRECTION,
                directionRightMissingTrials = DirectionValidationSummarizer.CONTROLLED_TRIALS_PER_DIRECTION,
                directionFrontMatched = 0,
                directionFrontMismatched = 0,
                directionFrontUnknownOrUnusable = 0,
                directionBackMatched = 0,
                directionBackMismatched = 0,
                directionBackUnknownOrUnusable = 0,
                directionLeftMatched = 0,
                directionLeftMismatched = 0,
                directionLeftUnknownOrUnusable = 0,
                directionRightMatched = 0,
                directionRightMismatched = 0,
                directionRightUnknownOrUnusable = 0,
                latestCuePresent = false,
                latestCueDirection = CallerDirection.UNKNOWN,
                latestDeliveryPresent = false,
                latestDeliverySource = "MISSING",
                latestDeliveryTotalCount = 0,
                latestDeliveryDeliveredCount = 0,
                latestDeliveryPhoneNotification = "MISSING",
                latestDeliveryPhoneVibration = "MISSING",
                latestDeliveryTts = "MISSING",
                latestDeliveryMetaDisplay = "MISSING",
                latestDeliveryAndroidXrDisplay = "MISSING",
                latestAudioDirectionSamplePresent = false,
                latestAudioDirectionStatus = "MISSING",
                latestAudioDirectionEvidenceLevel = "MISSING",
                latestAudioDirectionDirection = CallerDirection.UNKNOWN,
                latestAudioDirectionConfidenceBucket = "MISSING",
                latestAudioDirectionSampleRateHz = -1,
                latestAudioDirectionSamplesRead = 0,
                latestAudioDirectionMicrophoneInventoryCaptured = false,
                latestAudioDirectionAvailableMicrophoneCount = 0,
                latestAudioDirectionAvailablePositionKnownCount = 0,
                latestAudioDirectionAvailableOrientationKnownCount = 0,
                latestAudioDirectionActiveMicrophoneCaptured = false,
                latestAudioDirectionActiveMicrophoneCount = -1,
                latestAudioDirectionActiveChannelMappingCount = -1,
                serviceBridgePresent = false,
                falsePositiveRunPresent = false,
                falsePositiveRunActive = false,
                falsePositiveVerdict = "ERROR",
                message = error::class.java.simpleName,
            )
        }

        DiagnosticsLogger.info(
            "evidence_snapshot_completed",
            "passed" to result.passed,
            "profileCount" to result.profileCount,
            "eventCount" to result.eventCount,
            "latencyEventCount" to result.latencyEventCount,
            "latestDeliveryDeliveredCount" to result.latestDeliveryDeliveredCount,
            "directionTrialCount" to result.directionTrialCount,
            "feedbackCount" to result.feedbackCount,
        )
        setResultCode(if (result.passed) RESULT_CODE_PASS else RESULT_CODE_FAIL)
        setResultData(result.toResultData())
    }

    private data class EvidenceSnapshotResult(
        val passed: Boolean,
        val profileCount: Int,
        val eventCount: Int,
        val actionableEventCount: Int,
        val microphoneDisclosureAccepted: Boolean,
        val microphoneDisclosureVersion: String,
        val enabledAlertChannelCount: Int,
        val phoneNotificationEnabled: Boolean,
        val phoneVibrationEnabled: Boolean,
        val ttsEnabled: Boolean,
        val metaDisplayEnabled: Boolean,
        val androidXrDisplayEnabled: Boolean,
        val latencyEventCount: Int,
        val latestProcessingLatencyMillis: Long,
        val averageProcessingLatencyMillis: Long,
        val latencyOverTargetCount: Int,
        val feedbackCount: Int,
        val feedbackCorrect: Int,
        val feedbackFalsePositive: Int,
        val feedbackWrongDirection: Int,
        val feedbackWrongSpeaker: Int,
        val directionTrialCount: Int,
        val directionRequiredTrialsPerDirection: Int,
        val directionRequiredTotalTrials: Int,
        val directionMissingTotalTrials: Int,
        val directionControlledTrialTargetComplete: Boolean,
        val directionMatched: Int,
        val directionMismatched: Int,
        val directionUnknownOrUnusable: Int,
        val directionFrontTrials: Int,
        val directionBackTrials: Int,
        val directionLeftTrials: Int,
        val directionRightTrials: Int,
        val directionFrontMissingTrials: Int,
        val directionBackMissingTrials: Int,
        val directionLeftMissingTrials: Int,
        val directionRightMissingTrials: Int,
        val directionFrontMatched: Int,
        val directionFrontMismatched: Int,
        val directionFrontUnknownOrUnusable: Int,
        val directionBackMatched: Int,
        val directionBackMismatched: Int,
        val directionBackUnknownOrUnusable: Int,
        val directionLeftMatched: Int,
        val directionLeftMismatched: Int,
        val directionLeftUnknownOrUnusable: Int,
        val directionRightMatched: Int,
        val directionRightMismatched: Int,
        val directionRightUnknownOrUnusable: Int,
        val latestCuePresent: Boolean,
        val latestCueDirection: CallerDirection,
        val latestDeliveryPresent: Boolean,
        val latestDeliverySource: String,
        val latestDeliveryTotalCount: Int,
        val latestDeliveryDeliveredCount: Int,
        val latestDeliveryPhoneNotification: String,
        val latestDeliveryPhoneVibration: String,
        val latestDeliveryTts: String,
        val latestDeliveryMetaDisplay: String,
        val latestDeliveryAndroidXrDisplay: String,
        val latestAudioDirectionSamplePresent: Boolean,
        val latestAudioDirectionStatus: String,
        val latestAudioDirectionEvidenceLevel: String,
        val latestAudioDirectionDirection: CallerDirection,
        val latestAudioDirectionConfidenceBucket: String,
        val latestAudioDirectionSampleRateHz: Int,
        val latestAudioDirectionSamplesRead: Int,
        val latestAudioDirectionMicrophoneInventoryCaptured: Boolean,
        val latestAudioDirectionAvailableMicrophoneCount: Int,
        val latestAudioDirectionAvailablePositionKnownCount: Int,
        val latestAudioDirectionAvailableOrientationKnownCount: Int,
        val latestAudioDirectionActiveMicrophoneCaptured: Boolean,
        val latestAudioDirectionActiveMicrophoneCount: Int,
        val latestAudioDirectionActiveChannelMappingCount: Int,
        val serviceBridgePresent: Boolean,
        val falsePositiveRunPresent: Boolean,
        val falsePositiveRunActive: Boolean,
        val falsePositiveVerdict: String,
        val message: String,
    ) {
        fun toResultData(): String =
            listOf(
                "passed=$passed",
                "profileCount=$profileCount",
                "eventCount=$eventCount",
                "actionableEventCount=$actionableEventCount",
                "microphoneDisclosureAccepted=$microphoneDisclosureAccepted",
                "microphoneDisclosureVersion=$microphoneDisclosureVersion",
                "enabledAlertChannelCount=$enabledAlertChannelCount",
                "phoneNotificationEnabled=$phoneNotificationEnabled",
                "phoneVibrationEnabled=$phoneVibrationEnabled",
                "ttsEnabled=$ttsEnabled",
                "metaDisplayEnabled=$metaDisplayEnabled",
                "androidXrDisplayEnabled=$androidXrDisplayEnabled",
                "latencyEventCount=$latencyEventCount",
                "latestProcessingLatencyMillis=$latestProcessingLatencyMillis",
                "averageProcessingLatencyMillis=$averageProcessingLatencyMillis",
                "latencyOverTargetCount=$latencyOverTargetCount",
                "feedbackCount=$feedbackCount",
                "feedbackCorrect=$feedbackCorrect",
                "feedbackFalsePositive=$feedbackFalsePositive",
                "feedbackWrongDirection=$feedbackWrongDirection",
                "feedbackWrongSpeaker=$feedbackWrongSpeaker",
                "directionTrialCount=$directionTrialCount",
                "directionRequiredTrialsPerDirection=$directionRequiredTrialsPerDirection",
                "directionRequiredTotalTrials=$directionRequiredTotalTrials",
                "directionMissingTotalTrials=$directionMissingTotalTrials",
                "directionControlledTrialTargetComplete=$directionControlledTrialTargetComplete",
                "directionMatched=$directionMatched",
                "directionMismatched=$directionMismatched",
                "directionUnknownOrUnusable=$directionUnknownOrUnusable",
                "directionFrontTrials=$directionFrontTrials",
                "directionBackTrials=$directionBackTrials",
                "directionLeftTrials=$directionLeftTrials",
                "directionRightTrials=$directionRightTrials",
                "directionFrontMissingTrials=$directionFrontMissingTrials",
                "directionBackMissingTrials=$directionBackMissingTrials",
                "directionLeftMissingTrials=$directionLeftMissingTrials",
                "directionRightMissingTrials=$directionRightMissingTrials",
                "directionFrontMatched=$directionFrontMatched",
                "directionFrontMismatched=$directionFrontMismatched",
                "directionFrontUnknownOrUnusable=$directionFrontUnknownOrUnusable",
                "directionBackMatched=$directionBackMatched",
                "directionBackMismatched=$directionBackMismatched",
                "directionBackUnknownOrUnusable=$directionBackUnknownOrUnusable",
                "directionLeftMatched=$directionLeftMatched",
                "directionLeftMismatched=$directionLeftMismatched",
                "directionLeftUnknownOrUnusable=$directionLeftUnknownOrUnusable",
                "directionRightMatched=$directionRightMatched",
                "directionRightMismatched=$directionRightMismatched",
                "directionRightUnknownOrUnusable=$directionRightUnknownOrUnusable",
                "latestCuePresent=$latestCuePresent",
                "latestCueDirection=${latestCueDirection.name}",
                "latestDeliveryPresent=$latestDeliveryPresent",
                "latestDeliverySource=$latestDeliverySource",
                "latestDeliveryTotalCount=$latestDeliveryTotalCount",
                "latestDeliveryDeliveredCount=$latestDeliveryDeliveredCount",
                "latestDeliveryPhoneNotification=$latestDeliveryPhoneNotification",
                "latestDeliveryPhoneVibration=$latestDeliveryPhoneVibration",
                "latestDeliveryTts=$latestDeliveryTts",
                "latestDeliveryMetaDisplay=$latestDeliveryMetaDisplay",
                "latestDeliveryAndroidXrDisplay=$latestDeliveryAndroidXrDisplay",
                "latestAudioDirectionSamplePresent=$latestAudioDirectionSamplePresent",
                "latestAudioDirectionStatus=$latestAudioDirectionStatus",
                "latestAudioDirectionEvidenceLevel=$latestAudioDirectionEvidenceLevel",
                "latestAudioDirectionDirection=${latestAudioDirectionDirection.name}",
                "latestAudioDirectionConfidenceBucket=$latestAudioDirectionConfidenceBucket",
                "latestAudioDirectionSampleRateHz=$latestAudioDirectionSampleRateHz",
                "latestAudioDirectionSamplesRead=$latestAudioDirectionSamplesRead",
                "latestAudioDirectionMicrophoneInventoryCaptured=$latestAudioDirectionMicrophoneInventoryCaptured",
                "latestAudioDirectionAvailableMicrophoneCount=$latestAudioDirectionAvailableMicrophoneCount",
                "latestAudioDirectionAvailablePositionKnownCount=$latestAudioDirectionAvailablePositionKnownCount",
                "latestAudioDirectionAvailableOrientationKnownCount=$latestAudioDirectionAvailableOrientationKnownCount",
                "latestAudioDirectionActiveMicrophoneCaptured=$latestAudioDirectionActiveMicrophoneCaptured",
                "latestAudioDirectionActiveMicrophoneCount=$latestAudioDirectionActiveMicrophoneCount",
                "latestAudioDirectionActiveChannelMappingCount=$latestAudioDirectionActiveChannelMappingCount",
                "serviceBridgePresent=$serviceBridgePresent",
                "falsePositiveRunPresent=$falsePositiveRunPresent",
                "falsePositiveRunActive=$falsePositiveRunActive",
                "falsePositiveVerdict=$falsePositiveVerdict",
                "message=$message",
            ).joinToString(";")
    }

    companion object {
        private const val RESULT_CODE_PASS = 100
        private const val RESULT_CODE_FAIL = 101
    }
}
